apiVersion: v1
kind: Service
metadata:
  creationTimestamp: null
  labels:
    app: picamera-app
  name: picamera-svc
spec:
  ports:
  - port: 80
    protocol: TCP
    targetPort: 5000
  selector:
    app: picamera-app
  type: LoadBalancer
status:
  loadBalancer: {}
